version: '3.1'

services:
  bot:
    image: bennythink/teletweet
    restart: on-failure
    volumes:
      - ./env/auth.json:/TeleTweet/teletweet/auth.json
    env_file:
      - env/teletweet.env

  web:
    image: bennythink/teletweet
    restart: always
    env_file:
      - env/teletweet.env
    working_dir: /TeleTweet/twauth-web
    command: python twauth.py
